//If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
//Find the sum of all the multiples of 3 or 5 below 1000.

array = [] //a place to store the values that are multplies of 3 or 5

for(i = 0; i < 1000; i++){  //the numbers below 1000
  if(i%3 === 0 || i%5===0){   // multiples of 3 OR 5
    array.push(i)  // put them in our array
  }
}

total = array.reduce(function(a, b){return a+b;})  // add up all the indexes in the array
console.log(total) //Bam!




//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
//the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.

//so im going to write the psuedo code for this one
 If less then 4 million, loop through numbers
 store numbers in an array called Fibonacci
 have another array called total
 grab the current number and get the last number
 add the two numbers together then add that too Fibonacci array
 after we go through all numbers, begin to loop through array
 add up all the even numbers and put them in total
 return total array
